-- Adicionar campos opcionais para a tabela empresas
ALTER TABLE empresas ADD COLUMN IF NOT EXISTS telefone VARCHAR(20);
ALTER TABLE empresas ADD COLUMN IF NOT EXISTS site VARCHAR(255);
ALTER TABLE empresas ADD COLUMN IF NOT EXISTS whatsapp VARCHAR(20);
ALTER TABLE empresas ADD COLUMN IF NOT EXISTS descricao TEXT;
ALTER TABLE empresas ADD COLUMN IF NOT EXISTS setor VARCHAR(50);
ALTER TABLE empresas ADD COLUMN IF NOT EXISTS porte VARCHAR(20);
ALTER TABLE empresas ADD COLUMN IF NOT EXISTS data_fundacao DATE;
ALTER TABLE empresas ADD COLUMN IF NOT EXISTS num_funcionarios INTEGER;

-- Campos de endereço
ALTER TABLE empresas ADD COLUMN IF NOT EXISTS cep VARCHAR(10);
ALTER TABLE empresas ADD COLUMN IF NOT EXISTS rua VARCHAR(255);
ALTER TABLE empresas ADD COLUMN IF NOT EXISTS numero VARCHAR(10);
ALTER TABLE empresas ADD COLUMN IF NOT EXISTS complemento VARCHAR(100);
ALTER TABLE empresas ADD COLUMN IF NOT EXISTS bairro VARCHAR(100);
ALTER TABLE empresas ADD COLUMN IF NOT EXISTS cidade VARCHAR(100);
ALTER TABLE empresas ADD COLUMN IF NOT EXISTS estado VARCHAR(2);